### ISSUE TITLE
Error happened!

### ISSUE THREAD

**Issue by Shokusei** [swacisko/ALGA#1]
Hello, @swacisko 

We tried to run ALGA, but an error occurred. I don't know why such an error occurs. I would appreciate it if you could tell me the reason.

(trinity) [iceplant4561@at137 output]$ ~/ALGA/ALGA --file1=output.0.fq --file2=output.1.fq --threads=10 --output=outprefix _\-\-error-rate=0.02_
first inStreamFilePath1: output.0.fq
inStreamFilePath1 = output.0.fq
fileName = output.0.fq
fileExtension = fq
fileNameNoExt = output.0
TEST_NAME = ALGA_output.0_scale55_noN
starting to read
s[i] = +[i] = s[i] = +   but s 0  but should be A,C,G,T,N or U

  but should be A,C,G,T,N or U

  but should be A,C,G,T,N or U

s[i] = +   but should be A,C,G,T,N or U
s[i] = F   but should be A,C,G,T,N or U
*** Error in `/home/iceplant4561/ALGA/ALGA': double free or corruption (!prev): 0x00000000006a3180 ***
s[i] = F   but should be A,C,G,T,N or U
Segmentation fault (core dumped)

**Comment by swacisko** [comment]
Thanks a lot for letting me know about the issue!
It seems, that ALGA did not recognize the "fq" extension. I commited a fix for that.

**Comment by Shokusei** [comment]
> Thanks a lot for letting me know about the issue! It seems, that ALGA did not recognize the "fq" extension. I commited a fix for that.

I appreciate it so much! 
After making contigs, what tools should I use to make scaffoldings?

**Comment by swacisko** [comment]
We did not do any specific tests for scaffolding, so I cannot recommend a scaffolder that would work best with ALGA. Please use some external scaffolders and choose the one that suits you best.

**Comment by swacisko** [comment]
> > Thanks a lot for letting me know about the issue! It seems, that ALGA did not recognize the "fq" extension. I commited a fix for that.
> 
> I appreciate it so much! After making contigs, what tools should I use to make scaffoldings?

We did not do any specific tests for scaffolding, so I cannot recommend a scaffolder that would work best with ALGA. Please use some external scaffolders and choose the one that suits you best.

**Comment by Shokusei** [comment]
I understand. Thanks a lot!
Please pray for my succession.
